stages:


  restructure:
    cmd: python3 src/restructure.py assets/data/raw/*.csv
    deps:
    - assets/data/raw
    - src/restructure.py
    outs:
    - assets/data/restructured

  featurize:
    cmd: python3 src/featurize.py assets/data/restructured/*.csv
    deps:
    - assets/data/restructured
    - src/featurize.py
    outs:
    - assets/data/featurized
    params:
    - featurize.delete
    - featurize.features
    - featurize.remove
    - featurize.breathing_min
    - featurize.breathing_max
    - featurize.heartrate_min
    - featurize.heartrate_max
    - featurize.scale
    - featurize.range_window
    - featurize.range_smoothing
    - featurize.slope_shift
    - featurize.slope_smoothing
    - featurize.slope_abs
    - featurize.diff_targets

  split:
    cmd: python3 src/split.py assets/data/featurized/*.csv
    deps:
    - assets/data/featurized
    - src/split.py
    outs:
    - assets/data/split
    params:
    - split.train_split

  scale:
    cmd: python3 src/scale.py assets/data/split/*.csv
    deps:
    - assets/data/split
    - src/scale.py
    outs:
    - assets/data/scaled
    params:
    - scale.method

  sequentialize:
    cmd: python3 src/sequentialize.py assets/data/scaled/*.npz
    deps:
    - assets/data/scaled
    - src/sequentialize.py
    outs:
    - assets/data/sequentialized
    params:
    - sequentialize.hist_size
    - sequentialize.use_elements
    - sequentialize.target_mean_window

  combine:
    cmd: python3 src/combine.py assets/data/sequentialized/*.npz
    deps:
    - assets/data/sequentialized
    - src/combine.py
    outs:
    - assets/data/combined

  train:
    cmd: python3 src/train.py assets/data/combined/train.npz
    deps:
    - assets/data/combined
    - src/train.py
    - src/model.py
    - src/autoencoder.py
    outs:
    - assets/models
    params:
    - train.net
    - train.n_epochs
    - train.batch_size
    - train.kernel_size
    - train.weigh_samples
    - train.autoencode

  evaluate:
    cmd: python3 src/evaluate.py assets/models/model.h5 assets/data/combined/test.npz
    deps:
    - assets/data/combined/test.npz
    - assets/models/model.h5
    - src/evaluate.py
    metrics:
    - assets/metrics/metrics.json:
        cache: false
    params:
    - evaluate.smooth_targets
