profile:

featurize:
  raw_subfolder:
  features:
      - B1_POSITION_VALUE
      - B1_SPEED_VALUE
  target: B1_CURRENT_VALUE

split:
  train_split: 0.1

scale:
  method: standard # choose between standard and minmax
  output: standard

sequentialize:
  # History window sample size
  hist_size: 50
  target_size: 50

train:
  net: cnn
  n_epochs: 30
  batch_size: 128
  kernel_size: 4    

evaluate:
