clean:
  classification: false
  combine_files: false
  correlation_metric: pearson
  input_max_correlation_threshold: 1.0
  onehot_encode_target: false
  percentage_zeros_threshold: 1.0
  target: Accel_FFT_Acc1_range1_Amplitudes_0
evaluate: null
featurize:
  add_rolling_features: false
  features: null
  remove_features: null
  rolling_window_size: 100
  target_min_correlation_threshold: 0.0
profile:
  dataset: ideko
scale:
  input: minmax
  output: null
sequentialize:
  future_predict: false
  overlap: 0
  shuffle_samples: false
  target_size: 1
  window_size: 15
split:
  calibrate_split: 0.0
  shuffle_files: false
  train_split: 0.7
train:
  batch_size: 256
  early_stopping: true
  kernel_size: 3
  learning_method: cnn
  n_epochs: 200
  patience: 40
  train: true
