profile:

featurize:
  raw_subfolder:
  features:
      - X1_POSITION_VALUE
      - X1_SPEED_VALUE
      - Y1_POSITION_VALUE
      - Y1_SPEED_VALUE
  target: Y1_CURRENT_VALUE

split:
  train_split: 0.5

scale:
  method: standard # choose between standard and minmax
  output: standard

sequentialize:
  # History window sample size
  hist_size: 9
  target_size: 9

train:
  net: cnn
  n_epochs: 100
  batch_size: 128
  kernel_size: 3
  early_stopping: True
  patience: 40

evaluate:
