clean:
    # dataset: Name of data set, which is the name of the subfolder in which the data
    # files resides: 'assets/data/raw/[dataset]/
    dataset: data01

    # combine_files: Whether to combine all files into one. 
    #
    # Sometimes it is desirable to keep files separated, for example when:
    # - Some specific files should be reserved for the test set.
    # - We are dealing with time series data, and do not want sequences to
    #   overlap across files.
    #
    combine_files: True

featurize:
    # Which features to use from the data set. If empty, all columns from input
    # files are used.
    features:
        # - X1_ActualVelocity
        # - X1_ActualAcceleration
        # - X1_CommandPosition
        # - X1_CommandVelocity

    # Name of target variable.
    target: X1_ActualPosition

split:
    train_split: 0.5
    calibrate_split: 0.3

scale:
    # Current available scaling methods are:
    # - standard
    # - minmax
    input: standard
    output: standard

sequentialize:
    # History window sample size
    hist_size: 10
    # Currently, a target_size greater than 1 is not supported if calibrate_split > 0
    target_size: 1

train:
    net: cnn
    n_epochs: 100
    batch_size: 128
    # Kernel size is only applicable for CNN
    kernel_size: 3
    early_stopping: True
    patience: 40

evaluate:
