profile:
    # dataset: Name of data set, which is the name of the subfolder in which the data
    # files resides: 'assets/data/raw/[dataset]/
    dataset: data_aero

clean:
    # target: Name of target variable.
    target: B1_CURRENT_VALUE
    # target: X1_ActualPosition

    # combine_files: Whether to combine all files into one. 
    #
    # Sometimes it is desirable to keep files separated, for example when:
    # - Some specific files should be reserved for the test set.
    # - We are dealing with time series data, and do not want sequences to
    #   overlap across files.
    #
    combine_files: False

    # percentage_zeros_threshold: If the fraction of zeros in a column is
    # larger than this threshold, the column is removed.
    percentage_zeros_threshold: 0.5

    # correlation_metric: Which metric to measure correlation by. Choose from:
    # - pearson
    # - spearman
    # - phi_k
    # - cramers
    # - kendall
    correlation_metric: pearson

    # correlation_threshold: If the correlation between two variables are
    # higher than this threshold, one of them will be removed. If the threshold
    # is set to 1.0, no variables will be removed.
    correlation_threshold: 1.0

featurize:
    # features: Which features to use from the data set. If empty, all columns
    # from input files are used.
    features:
        # - X1_ActualVelocity
        # - X1_ActualAcceleration
        # - X1_CommandPosition
        # - X1_CommandVelocity


split:
    train_split: 0.5
    calibrate_split: 0.3

scale:
    # Current available scaling methods are:
    # - standard
    # - minmax
    input: standard
    output: standard

sequentialize:
    # History window sample size
    hist_size: 10
    # Currently, a target_size greater than 1 is not supported if calibrate_split > 0
    target_size: 1

train:
    net: cnn
    n_epochs: 100
    batch_size: 128
    # Kernel size is only applicable for CNN
    kernel_size: 3
    early_stopping: True
    patience: 40

evaluate:
