profile:

featurize:
  dataset: data01
  features:
      - X1_ActualVelocity
      - X1_ActualAcceleration
      - X1_CommandPosition
      - X1_CommandVelocity
  target: X1_ActualPosition

split:
  train_split: 0.1
  calibrate_split: 0.3

scale:
  method: standard # choose between standard and minmax
  output: standard

sequentialize:
  # History window sample size
  hist_size: 9
  # Currently, a target_size greater than 1 is not supported if calibrate_split > 0
  target_size: 1

train:
  net: cnn
  n_epochs: 10
  batch_size: 128
  kernel_size: 3
  early_stopping: True
  patience: 40

evaluate:
