profile:

featurize:
  raw_subfolder:
  features:
      - Y1_POSITION_VALUE
      - Y1_SPEED_VALUE
  target: Y1_CURRENT_VALUE

split:
  train_split: 0.5

scale:
  method: standard # choose between standard and minmax
  output: standard

sequentialize:
  # History window sample size
  hist_size: 50
  target_size: 30

train:
  net: cnn
  n_epochs: 30
  batch_size: 128
  kernel_size: 4    
  early_stopping: True

evaluate:
